spring.application.name=BankingSystem
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/banking_system
spring.datasource.username=root
spring.datasource.password=12345@1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

debug=true

# Custom path for Swagger UI (Default: /swagger-ui.html)
springdoc.swagger-ui.path=/swagger-ui.html
# Custom path for OpenAPI JSON (Default: /v3/api-docs)
springdoc.api-docs.path=/v3/api-docs

# Respect ngrok / reverse-proxy forwarded headers when generating links and server URLs
server.forward-headers-strategy=framework

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.batch.job.enabled=false